name: uv_ble_sdk
description: "SDK for KernelMeds UV Phototherapy device."
version: 0.0.4
homepage: ""

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_blue_plus: ^1.32.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:

  plugin:
    platforms:
      android:
        package: com.napses.uv.ble.uv_ble_sdk
        pluginClass: UvBleSdkPlugin
      ios:
        pluginClass: UvBleSdkPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
